---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: airflow
spec:
  interval: 1m
  url: https://github.com/airflow-helm/charts.git
  ref:
    tag: airflow-8.5.3
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  dependsOn:
    - name: airflow-base
  interval: 5m
  chart:
    spec:
      chart: ./charts/airflow
      sourceRef:
        kind: GitRepository
        name: airflow
        namespace: airflow
      interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  targetNamespace: airflow
