---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplbjdab-xjam-rg
      identity: osdu-self-cplbjdab-xjam-osdu-identity
      identity_id: 26f6f855-6a5f-4b7e-8cf1-ed7f7fab7508
      keyvault: osdu-self-cplbjd-xjam-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcplbjdxjamcr.azurecr.io
