---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cpldccaa-28du-rg
      identity: osdu-self-cpldccaa-28du-osdu-identity
      identity_id: 076ca186-4cd8-4dc9-8bce-139e5635bd78
      keyvault: osdu-self-cpldcc-28du-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcpldcc28ducr.azurecr.io
