---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    flower:
      enabled: false
    airflow:
      dbMigrations:
        podLabels:
          aadpodidbinding: "osdu-identity"
      sync:
        podLabels:
          aadpodidbinding: "osdu-identity"
      extraVolumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
      extraVolumes:
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
      scheduler:
        replicas: 2
        podLabels:
          aadpodidbinding: "osdu-identity"
      web:
        replicas: 1
        podLabels:
          aadpodidbinding: "osdu-identity"
      workers:
        replicas: 3
        podLabels:
          aadpodidbinding: "osdu-identity"

