---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplcfhch-dmii-rg
      identity: osdu-self-cplcfhch-dmii-osdu-identity
      identity_id: c9cc119c-5415-419b-941c-8d4088ae1afb
      keyvault: osdu-self-cplcfh-dmii-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcplcfhdmiicr.azurecr.io
