---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cpldcedb-svet-rg
      identity: osdu-self-cpldcedb-svet-osdu-identity
      identity_id: 2f34a8e0-0288-44b6-a46a-05e475e28151
      keyvault: osdu-self-cpldce-svet-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcpldcesvetcr.azurecr.io
