---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplbdjdi-p5xe-rg
      identity: osdu-self-cplbdjdi-p5xe-osdu-identity
      identity_id: 697465a4-8611-446a-b670-9ee67e6872d7
      keyvault: osdu-self-cplbdj-p5xe-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcplbdjp5xecr.azurecr.io
