---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplbhcdc-6099-rg
      identity: osdu-self-cplbhcdc-6099-osdu-identity
      identity_id: 9b7856fd-a5b6-4164-abe9-24c1164cff0d
      keyvault: osdu-self-cplbhc-6099-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
    image:
      repository: osduselfcplbhc6099cr.azurecr.io
