---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    ########################################
    ## CONFIG | Airflow Configs
    ########################################
    airflow:
      dbMigrations:
        podLabels:
          aadpodidbinding: "airflow-identity"
      sync:
        podLabels:
          aadpodidbinding: "airflow-identity"
      extraVolumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
      extraConfigmapMounts:
        - name: remote-log-config
          mountPath: /opt/airflow/config
          configMap: airflow-remote-log-config
          readOnly: true
        - name: celery-config
          mountPath: /opt/celery
          configMap: celery-config
          readOnly: true
      extraVolumes:
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
      extraPipPackages: []
      config:
        AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
        AIRFLOW__WEBSERVER__BASE_URL: "https://osdu-self-dplfhag-73n2-gw.westeurope.cloudapp.azure.com/airflow"
      extraEnv:
        - name: CLOUD_PROVIDER
          value: "azure"
        - name: AIRFLOW_VAR_KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-config
              key: ENV_KEYVAULT
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet-key
        - name: AIRFLOW_CONN_AZ_LOG
          valueFrom:
            secretKeyRef:
              name: airflow
              key: remote-log-connection
        - name: AIRFLOW_VAR_AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: tenantid
        - name: AIRFLOW_VAR_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientid
        - name: AIRFLOW_VAR_AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientpassword
        - name: AIRFLOW_VAR_AAD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: application-appid
        - name: AIRFLOW_VAR_APPINSIGHTS_KEY
          valueFrom:
            secretKeyRef:
              name: central-logging
              key: appinsights
        - name: AIRFLOW_VAR_AZURE_DNS_HOST
          value: osdu-self-dplfhag-73n2-gw.westeurope.cloudapp.azure.com
          # Needed for installing python osdu python sdk.
        - name: CI_COMMIT_TAG
          value: "v0.13.0"
        - name: BUILD_TAG
          value: "v0.13.0"
        - name: AIRFLOW_VAR_ENTITLEMENTS_MODULE_NAME
          value: "entitlements_client"
        - name: AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH
          value: "/opt/airflow/dags/configs/dataload.ini"
        - name: AIRFLOW_VAR_CORE__SERVICE__SCHEMA__URL
          value: "http://schema.osdu-azure.svc.cluster.local/api/schema-service/v1"
        - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH__URL
          value: "http://search.osdu-azure.svc.cluster.local/api/search/v2"
        - name: AIRFLOW_VAR_CORE__SERVICE__STORAGE__URL
          value: "http://storage.osdu-azure.svc.cluster.local/api/storage/v2"
        - name: AIRFLOW_VAR_CORE__SERVICE__FILE__HOST
          value: "http://file.osdu-azure.svc.cluster.local/api/file"
        - name: AIRFLOW_VAR_CORE__SERVICE__WORKFLOW__HOST
          value: "http://workflow.osdu-azure.svc.cluster.local/api/workflow/v1"
        - name: AIRFLOW_VAR_CORE__SERVICE__DATASET__HOST
          value: "http://dataset.osdu-azure.svc.cluster.local/api/dataset/v1"
        - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH_WITH_CURSOR__URL
          value: "http://search.osdu-azure.svc.cluster.local/api/search/v2/query_with_cursor"
        - name: AIRFLOW_VAR_CORE__SERVICE__PARTITION__URL
          value: "http://partition.osdu-azure.svc.cluster.local/api/partition/v1"
        - name: AIRFLOW_VAR_CORE__SERVICE__LEGAL__HOST
          value: "http://legal.osdu-azure.svc.cluster.local/api/legal/v1"
        - name: AIRFLOW_VAR_CORE__SERVICE__ENTITLEMENTS__URL
          value: "http://entitlements.osdu-azure.svc.cluster.local/api/entitlements/v2"
        - name: AIRFLOW_VAR_ENV_VARS_ENABLED
          value: "true"

    ###################################
    ## COMPONENT | Airflow Scheduler
    ###################################
    scheduler:
      replicas: 2
      podLabels:
        aadpodidbinding: "airflow-identity"

    ###################################
    ## COMPONENT | Airflow Webserver
    ###################################
    web:
      replicas: 1
      podLabels:
        aadpodidbinding: "airflow-identity"

    ###################################
    ## COMPONENT | Airflow Workers
    ###################################
    workers:
      replicas: 3
      podLabels:
        aadpodidbinding: "airflow-identity"

    ###################################
    ## COMPONENT | Flower
    ###################################
    flower:
      enabled: false

    ###################################
    ## CONFIG | Airflow Logs
    ###################################
    logs:
      path: /opt/airflow/logs
      persistence:
        enabled: false

    ###################################
    ## CONFIG | Airflow DAGs
    ###################################
    dags:
      path: /opt/airflow/dags
      persistence:
        enabled: false
        existingClaim: airflowdag-pvc
        subPath: "dags"

    ###################################
    ## CONFIG | Kubernetes Ingress
    ###################################
    ingress:
      enabled: true
      web:
        annotations:
          kubernetes.io/ingress.class: azure/application-gateway
          appgw.ingress.kubernetes.io/request-timeout: "300"
          appgw.ingress.kubernetes.io/connection-draining: "true"
          appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
          cert-manager.io/cluster-issuer: letsencrypt-prod-dns
          cert-manager.io/acme-challenge-type: http01
        path: "/airflow"
        host: osdu-self-dplfhag-73n2-gw.westeurope.cloudapp.azure.com
        livenessPath: "/airflow/health"
        tls:
          enabled: true
          secretName: osdu-certificate
        precedingPaths:
          - path: "/airflow/*"
            serviceName: airflow-web
            servicePort: 8080

    ###################################
    ## DATABASE | PgBouncer
    ###################################
    pgbouncer:
      enabled: false

    ###################################
    ## DATABASE | Embedded Postgres
    ###################################
    postgresql:
      enabled: false

    ###################################
    ## DATABASE | External Database
    ###################################
    externalDatabase:
      type: postgres
      host: osdu-self-dplfhag-73n2-pg.postgres.database.azure.com
      user: osdu_admin@osdu-self-dplfhag-73n2-pg
      passwordSecret: "postgres"
      passwordSecretKey: "postgres-password"
      port: 5432
      properties: "?sslmode=require"
      database: airflow

    ###################################
    ## DATABASE | Embedded Redis
    ###################################
    redis:
      enabled: false

    ###################################
    ## DATABASE | External Redis
    ###################################
    externalRedis:
      host: osdu-self-dplfhag-73n2-cache.redis.cache.windows.net
      passwordSecret: "redis"
      passwordSecretKey: "redis-password"
      port: 6380

    ###################################
    ## CONFIG | ServiceMonitor (Prometheus Operator)
    ###################################
    serviceMonitor:
      enabled: false

    ###################################
    ## CONFIG | PrometheusRule (Prometheus Operator)
    ###################################
    prometheusRule:
      enabled: false
