---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplbfih-6jes-rg
      identity: osdu-self-cplbfih-6jes-osdu-identity
      identity_id: 7ce7f6de-7b43-4256-af98-df518630f7f8
      keyvault: osdu-self-cplbfi-6jes-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
