---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplcfgfg-8hkb-rg
      identity: osdu-self-cplcfgfg-8hkb-osdu-identity
      identity_id: c2412411-4f07-44dc-9847-960243484d9c
      keyvault: osdu-self-cplcfg-8hkb-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
