---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
        appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
