---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplcibed-9y51-rg
      identity: osdu-self-cplcibed-9y51-osdu-identity
      identity_id: 7c8bd356-cc9a-4832-b924-ff5dcb307376
      keyvault: osdu-self-cplcib-9y51-kv
      appid: f78ba065-2926-4df4-a2a2-c8cd2657c8dd
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
