name: "4. Stamp Images"

on:
  workflow_dispatch:

env:
  CLI_VERSION: 2.40.0

  OSDU_VERSION: 0.16.0
  INGESTION_DAG_VERSION: 0.12.0

jobs:
  image-data:
    name: Import Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve Env Variables
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)
            CLIENT_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/aad-client-id --query value -otsv)
            TENANT_ID=$(az account show --query tenantId -otsv)
            DP_GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            DNS_HOST=$(az network public-ip list --resource-group $DP_GROUP --query [].dnsSettings.fqdn -otsv)

            echo "GROUP=$GROUP" >> $GITHUB_ENV
            echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
            echo "TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
            echo "DNS_HOST=$DNS_HOST" >> $GITHUB_ENV

      - name: ACR Import
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            REGISTRY=$(az acr list -g $GROUP --query [0].name -otsv)
            jq -c '.[]' $GITHUB_WORKSPACE/configuration/release_$OSDU_VERSION.json | while read i; do
              NAME=$(echo $i | jq -r '.name')
              IMAGE=$(echo $i | jq -r '.image')
              TAG=$(echo $i | jq -r '.tag')
              echo "--------------------------------------------------------------------------------------------------"
              echo "Import $IMAGE"
              echo "--------------------------------------------------------------------------------------------------"
              az acr import \
                --name $REGISTRY \
                --source $IMAGE \
                --image $NAME:$TAG \
                --force
              az acr repository show \
                --name $REGISTRY \
                --image $NAME:$TAG -ojson
            done

  workflow-data:
    name: Load Airflow - FileShare
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Upload Ingestion Manifest
      #   env:
      #     SERVICE: ingestion-dags
      #     FOLDER: src/osdu_dags
      #     FILE_SHARE: airflowdags
      #   uses: Azure/cli@1.0.4
      #   with:
      #     azcliversion: ${{ env.CLI_VERSION }}
      #     inlineScript: |
      #       mkdir ${{ env.RUNNER_TEMP }}/results
      #       curl -sSL -o ${{ env.RUNNER_TEMP }}/download.tar.gz https://community.opengroup.org/osdu/platform/data-flow/ingestion/${{ env.SERVICE }}/-/archive/v${{ env.INGESTION_DAG_VERSION }}/${{ env.SERVICE }}-v${{ env.INGESTION_DAG_VERSION }}.tar.gz
      #       tar -xzvf ${{ env.RUNNER_TEMP }}/download.tar.gz -C ${{ env.RUNNER_TEMP }}/results --strip-components=3 ${{ env.SERVICE }}-v${{ env.INGESTION_DAG_VERSION }}/${{ env.FOLDER }}
      #       cd ${{ env.RUNNER_TEMP }}/results && zip -r ../manifest-ingestion-dags.zip . && cd ..

      #       GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
      #       ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

      #       az storage file upload \
      #         --account-name $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage --query value -otsv) \
      #         --account-key $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage-key --query value -otsv) \
      #         --share-name ${{ env.FILE_SHARE }} \
      #         --source ${{ env.RUNNER_TEMP }}/manifest-ingestion-dags.zip

      - name: Upload Local DAGS
        env:
          FILE_SHARE: airflowdags
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

            az storage file upload-batch \
              --account-name $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage --query value -otsv) \
              --account-key $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage-key --query value -otsv) \
              --destination ${{ env.FILE_SHARE }} \
              --source $GITHUB_WORKSPACE/src/${{ env.FILE_SHARE }} \
              --pattern "*.ini"

            az storage file upload-batch \
              --account-name $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage --query value -otsv) \
              --account-key $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage-key --query value -otsv) \
              --destination ${{ env.FILE_SHARE }} \
              --source $GITHUB_WORKSPACE/src/${{ env.FILE_SHARE }} \
              --pattern "*.py"
